name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '6,26,46 * * * *'

permissions:
  contents: write
  pages: write
  
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Fetch latest data
      run: |-
        curl https://api.2626.com.cn/api/getCaipiaoInfo | jq . > incidents.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
